version: '2'
services:
  miproyecto-app:
    image: miproyecto
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://miproyecto-mysql:3306/miproyecto?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://miproyecto-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://miproyecto-elasticsearch:9200
    ports:
      - 8080:8080
  miproyecto-mysql:
    extends:
      file: mysql.yml
      service: miproyecto-mysql
  miproyecto-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: miproyecto-elasticsearch
